title:              Jigar Parekh
email:              jigar.parekh.ds@gmail.com
description:        PORTFOLIO
author:             Jigar Parekh
baseurl:            ""
url:                "https://jigarparekh279.github.io"

# Social Profiles
twitter_username:
github_username:    jigarparekh279
facebook_username:
instagram_username:
linkedin_username:  jigarparekh279


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site